name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: PHP Tests on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 2
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          extensions: mbstring,curl
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Install React HTTP
        run: composer require react/http
      - name: Run PHPStan
        run: composer run-script lint:ci
      - name: Create test directory
        run: mkdir -p test-results/behat
        shell: bash
      - name: BDD Tests
        run: vendor/bin/behat --config behat.yml -f pretty -o std -f junit -o test-results/behat/
        shell: bash
